name: Build search index, feed & sitemap

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # every Monday 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml python-dateutil
      - name: Generate site artifacts
        run: |
          mkdir -p scripts
          python scripts/generate_site_artifacts.py --site-url "https://valihakuryuko.github.io"
      - name: Commit & push changes
        run: |
          if git status --porcelain | grep -E "feed.xml|sitemap.xml|robots.txt|search_index.json|search.html"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add feed.xml sitemap.xml robots.txt search_index.json search.html || true
            git commit -m "chore(ci): auto-generate feed, sitemap, search index"
            git push
          else
            echo "No changes to commit."
          fi
